<a href="https://colab.research.google.com/github/Deepika-Kondapalli3/ml-practice/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Assignment

---

**Instructions**

1. **Read Each Question Carefully**: Understand what each question is asking before starting.

2. **Complete the Functions**: For each question, you’ll find a partially completed function in the code cell. Fill in the missing parts to complete the function according to the requirements.

3. **Test Your Function**: After completing each function, run the cell to test if your function works correctly.

4. **Answer All Questions**: Ensure you complete all functions. Each question targets different aspects of NumPy.

5. **Download Your Notebook**: Once you’ve finished and tested all functions, download your notebook file (.ipynb) by selecting `File > Download > Download .ipynb`.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated platform for submission.

7. **Verify Your Submission**: Check that you have submitted the correct file and that it is not corrupted. Resubmit if necessary.

* Note: Don't change or replace any of the given arrays or variables, use it as given and write your code.

Good luck, and happy coding!

---

## Import library
- Do not modify the given attributes. Execute the below code cells sequencially to get the data.

In [1]:
import numpy as np

---
---
**1.Complete the given code which takes an array of salaries as input and prints mean, median of the salaries** <br>
- Input : An array of salaries <br>
- Output : mean, median (print in single same order)

In [2]:
import numpy as np
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000, 110000, 50000])

# Write the code here
mean =np.mean(salaries)
median =np.median(salaries)
print(mean,median)

76250.0 75000.0


---
---
**2. Complete the given code which takes an array of salaries as input and prints variance and standard deviation of the salaries with 2 decimals** <br>
- Input  : An array of salaries <br>
- Output : variance

In [3]:
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000, 110000, 50000])

# Write the code here
variance =np.var(salaries).round(2)
standard_deviation =np.std(salaries).round(2)
print(variance, standard_deviation)

448437500.0 21176.34


---
---
**3. Write a code to get the quartiles (Q1, Q2, Q3) of an array of salaries.** <br>
- Input  : An array of salaries <br>
- Output : q1, q2, q3

In [26]:
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000, 110000, 50000])

# Write the code here
q1=np.percentile(salaries,25)
q2=np.percentile(salaries,50)
q3=np.percentile(salaries,75)
print(q1,q2,q3)


57500.0 75000.0 92500.0


---
---
**4. Write a code to get the z_scores which takes the given *nums* array as input and returns an array having the z_scores of all elements** <br>
- Input  : An array of elements (Use only the given array) <br>
- Output : An array having **z_scores**

In [6]:
nums = np.array([10, 20, 0, 40, 50, 60])

# Write your code here
z_scores = (nums-np.mean(nums))/np.std(nums)
print(z_scores)

[-0.9258201  -0.46291005 -1.38873015  0.46291005  0.9258201   1.38873015]


---
---
**5. Write a code to get the variance which takes the given array of salaries and returns the variance without using the inbuilt variance function.** <br>
 - Input  : An array of salaries
 - Output : variance

- Hints:
 - Use the formula - variance = sum ((xi - μ)^2) / N.
 - Calculate the mean to compute the variance

In [13]:
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000, 110000, 50000])

# Write your code here
var = np.sum((salaries - np.mean(salaries)) ** 2) / (len(salaries))
print(var)

448437500.0


---
---
**6. Write a code to get the computative salaries which takes the given array of salaries and returns all salaries which are higher than the mean salary.** <br>
 - Input  : An array of salaries
 - Output : An array of salaries higher than the mean.

In [14]:
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000, 110000, 50000])

# Write the code here to find all salaries higher than the mean
higher_salaries =salaries[salaries>np.mean(salaries)]
print(higher_salaries)

[ 80000  90000 100000 110000]


---
---
**7. Write a code to get the cumulative sums which takes two given arrays of same size and returns the difference between cumulative sums at each position.** <br>
- Input  : Use the given two arrays
- Output : difference in cumulative sums



In [15]:
a1 = np.array([10,12,14,8,7,9,20])
a2 = np.array([12,11,8,10,9,13,7])

# write your code here to compute cumulative sums
cumsum_a1 =np.cumsum(a1)
cumsum_a2 =np.cumsum(a2)

# Compute difference
diff =cumsum_a1-cumsum_a2
print(diff)

[-2 -1  5  3  1 -3 10]


---
---
**8. Given two arrays a1 and a2 of shape (4, 3) with integers between 10 to 50 (inclusive) and concatenate them along axis 0.**

In [17]:
a1 = np.array([[10, 20, 30], [15, 25, 35], [40, 50, 45], [30, 35, 40]])
a2 = np.array([[12, 22, 32], [17, 27, 37], [42, 47, 52], [31, 36, 41]])

# write your code here
concatenated =np.concatenate((a1,a2),axis=0)
print(concatenated)

[[10 20 30]
 [15 25 35]
 [40 50 45]
 [30 35 40]
 [12 22 32]
 [17 27 37]
 [42 47 52]
 [31 36 41]]


**9. Write a code to calculate the interquartile range (IQR) of given array of salaries.**

In [27]:
salaries = np.array([50000, 60000, 70000, 80000, 90000, 100000])

# Write the code here
q3=np.percentile(salaries,75)
q1= np.percentile(salaries,25)
iqr =q3-q1
print(iqr)

25000.0


**10. Given a 2D NumPy array a1 with shape (4, 3), reshape it into a 2D array with 2 rows and 6 columns.**

In [20]:
a1 = np.array([[10, 20, 30], [15, 25, 35], [40, 50, 45], [30, 35, 40]])

# Write the code here
reshaped_array= a1.reshape(2,6)
print(reshaped_array)

[[10 20 30 15 25 35]
 [40 50 45 30 35 40]]


## --- END ---