<a href="https://colab.research.google.com/github/Deepika-Kondapalli3/ml-practice/blob/main/Numpy_Practice_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

## Import library
- Do not modify the given attributes. Execute the below code cells sequencially to get the data.

In [1]:
import numpy as np

Q.1 Create a 5x5 array, with numbers ranging from 1-25 and save it in `matrix` variable.
(Use the same `matrix` creation code in all the code cells were questions are based on matrix.)

In [2]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Q.2 select the subset from `matrix`
```python
Expected output
[[12,13,14,15],
 [17,18,18,20],
 [22,23,24,25]]
```

In [52]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
subset_q2 =matrix[2:,1:]
print(subset_q2)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Q.3 Select the value 20 from the `matrix`

In [4]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
value_20 =matrix[3,4]
print(value_20)

20


Q.4 Select the below subset.(Use `matrix`)
```python
Expected output
[[2],
 [7],
 [12]]
```


In [12]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
subset_q4 =matrix[0:3,1]
print(np.array(subset_q4).reshape(3,1))

[[ 2]
 [ 7]
 [12]]


Q.5 Select the below subset. (Use `matrix`)
```python
Expected output
[21,22,23,24,25]
```

In [14]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
subset_q5 =matrix[4]
print(subset_q5)

[21 22 23 24 25]


Q.6 Select the subset below (Use `matrix`)
```python
Expected output
[[16,17,18,19,20],
 [21,22,23,24,25]]
```



In [16]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
subset_q6 =matrix[3:]
print(subset_q6)

[[16 17 18 19 20]
 [21 22 23 24 25]]


Q.7 Get the sum of all the values in `matrix`. (Expected Ans : 325)

In [17]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
sum_matrix =np.sum(matrix)
print(sum_matrix)

325


Q.8 Get the standard deviation of the values in `matrix`(Expected Ans : 7.211102551)

In [57]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
std_dev_matrix =np.std(matrix).round(9)
print(std_dev_matrix)

7.211102551


Q.9 Get the sum of all the columns in `matrix`. (Expected Ans: array([55,60,65,70,75])

In [20]:
# write your code here
matrix =np.arange(1,26).reshape(5,5)
sum_columns =np.sum(matrix, axis=0)
print(sum_columns)

[55 60 65 70 75]


Q.10 Reverse a 1D array of 1 to 10.

In [27]:
# write your code here
array_to_reverse =np.arange(1,11)
reversed_array =array_to_reverse[::-1]
print(reversed_array)

[10  9  8  7  6  5  4  3  2  1]


Q.11 Find indices of non-zero elements from [10,20,0,0,40,0]

In [33]:
# write your code here
non_zero_indices =np.array([10,20,0,0,40,0])
print(np.nonzero(non_zero_indices))

(array([0, 1, 4]),)


Q.12 Create a 10x10 array with 1 on the border and 0 inside.

In [53]:
# write your code here
bordered_array =np.zeros((10,10))
bordered_array[0,:]=1
bordered_array[-1,:]=1
bordered_array[:,0]=1
bordered_array[:,-1]=1
print(bordered_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q. 13 Create 5x5 array and fill it with the cheakerboard pattern.

In [56]:
# write your code here
checkerboard =np.ones((5,5))
checkerboard[::2,1::2]=0
checkerboard[1::2,::2]=0
print(checkerboard)

[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


Q.14 Create a numpy array of size 10 with values ranging from 0 to 1, both excluded.

In [55]:
# write your code here
excluded_array =np.linspace(0.1,0.9,10)
print(excluded_array)

[0.1        0.18888889 0.27777778 0.36666667 0.45555556 0.54444444
 0.63333333 0.72222222 0.81111111 0.9       ]


Q.15 Create the matrix as array_5x5 (0-25) and swap first two rows.

In [51]:
# write your code here
array_5x5 =np.arange(25).reshape(5,5)
array_5x5[[0,1]]=array_5x5[[1,0]]
print(array_5x5)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# End!